### ISSUE TITLE
Unable to find the "Favorites" pane anywhere

### ISSUE THREAD

**Issue by antiflu** [facelessuser/FavoriteFiles#11]
Can see the command add to favorites in command pane, but then cannot see the list of favorites anywhere

ST3 on Linux Mint

**Comment by facelessuser** [comment]
I am not sure what your problem is;  can you elaborate? Once a file had been added, you should be able to use the "FavoriteFiles: Open file(s)"  (or something like that) and see the added files.

Please be more specific on what you have tried,  what you expected to happen vs what actually happened and also post any errors found in the console. 

Also,  if you just installed via package control,  a restart may be needed.   If you installed manually,  please install via package control.

**Comment by antiflu** [comment]
Thanks for your answer. I was expecting a "Favorites" pane somewhere to pop up so I can see my Favorite files always in a list (Such as the "Folders" or "Opened files" panes on the left). Apparently it's not the case. I will try to get used to Ctrl-Shift-P and then going to Favorite files.

Maybe it would be a good idea to stress in the documentation that this plugin does not offer a "Favorites" pane

**Comment by facelessuser** [comment]
No where in the docs does it imply there is a "Favorties" panel.  A matter of fact, the first command listed in the docs is the open file command implying that to open a favorite file you must run that command: http://facelessuser.github.io/FavoriteFiles/usage/#favorite-files-open-file.
