### ISSUE TITLE
When only 1 tab open, adding favorite file fails.

### ISSUE THREAD

**Issue by gabrieljenik** [facelessuser/FavoriteFiles#7]

**Comment by facelessuser** [comment]
Originally I added in some hacks for ST3, but it seems I need re-evaluate some things.  I haven't used FavoriteFiles in a bit, so it hasn't gotten the attention it deserves.  I will look into FavoriteFiles very soon.  I'm a bit disappointed I left it in it's current state.  I need to get ST3 support humming again.

**Comment by facelessuser** [comment]
Commit https://github.com/facelessuser/FavoriteFiles/commit/a47bc4b6b981dab6526a12b40892d31bac02c445 should fix this.  I need to test this on the last stable beta before I release; hopefully I will get to it tomorrow.

**Comment by facelessuser** [comment]
Working now across platforms.  Just need to test last beta now.

**Comment by facelessuser** [comment]
Got around to testing the last stable beta.  The code I removed that has everything working okay on latest dev release, no longer lets FavoriteFiles work on the last stable beta.  This isn't  a big deal though, it just means I need to revisit the old hack in a cleaner way that works on the bleeding edge and old builds.

I am hoping within the week I will be able to close this.

**Comment by gabrieljenik** [comment]
Thanks! No rushes on my side, so take as much time as you need!

**Comment by facelessuser** [comment]
Sounds like Jon is getting close to releasing a new public beta of Sublime.  If that is the case, recent Sublime builds work with my latest unreleased commits, and I may just force people to upgrade to the latest beta instead of adding back in an elaborate hack.

The problem is that in older builds of Sublime 3, you could launch a quick panel, and when it does it's callback on selection, the panel is still open while you evaluate the return value.  So if you try and re-open the quick panel, you get an error as the panel is already open and remains open until the callback finishes.  Apparently this behavior has been changed in builds since 3065.

Now the problem on my end is that my hack was to reopen the panel via a `sublime.set_timeout` which gave the panel time to close before opening a new one...but the hack was pretty sloppy and obviously not tested extensively and didn't work well. So I gutted it when I saw this issue to evaluate if the original problem still existed, and it worked on the 3070+ showing that Jon changed the behavior back to work as it did on ST2.

So, if he releases the beta before I get around to adding back in a more solid workaround, I will probably just note in an upgrade message that people need to upgrade, and tag a new release and forget all about adding in the original hack :wink: .

**Comment by facelessuser** [comment]
Looks like beta 3080 is out.  I will probably make a new release soon with a notice to upgrade to 3078 or greater.

**Comment by facelessuser** [comment]
A new release as been tagged [`ST3 1.4.0`](https://github.com/facelessuser/FavoriteFiles/releases/tag/st3-1.4.0).  This release will alert the user they need to upgrade to 3080+ to have full use of Favorite Files again.  All functionality should be present in this release.

**Comment by facelessuser** [comment]
@gabrieljenik, Let me know if your issue is resolved in the latest release so I can close this out.

**Comment by gabrieljenik** [comment]
Works like a charm!
